export enum RouteMenu {
    STORAGE_PLAN = 'storage_plan',
    EXIT_PLAN = 'exit_plan',
    WAREHOUSE_MANAGEMENT = 'warehouses',
    INSERT_WAREHOUSE = 'warehouses/insert',
    OPERATING_INSTRUCTIONS = 'operating_instructions',
    OPERATIONS_RECORD = 'operations_record',
    INSERT_USER = 'users/insert_user',
    LIST_USERS = 'users',
    INSERT_STAFF = 'insert_staff',
    LIST_STAFF = 'staff',
    INSERT_WAREHOUSE_CARGO_STATION = 'warehouse_cargo_station/insert',
    LIST_WAREHOUSE_CARGO_STATION = 'warehouse_cargo_station',
    INSERT_PAYMENT_METHOD = 'insert_payment_method',
    LIST_PAYMENT_METHODS = 'payment_methods',
    INSERT_USER_LEVEL = 'insert_user_level',
    LIST_USER_LEVELS = 'user_levels',
};