export enum RouteMenu {
    STORAGE_PLAN = 'storage_plan',
    INSERT_STORAGE_PLAN = 'storage_plan/insert',
    EXIT_PLAN = 'exit_plan',
    WAREHOUSE_MANAGEMENT = 'warehouses',
    INSERT_WAREHOUSE = 'warehouses/insert',
    OPERATING_INSTRUCTIONS = 'operation_instruction',
    OPERATIONS_RECORD = 'operations_record',
    INSERT_USER = 'users/insert_user',
    LIST_USERS = 'users',
    INSERT_STAFF = 'staff/insert_staff',
    LIST_STAFF = 'staff',
    INSERT_WAREHOUSE_CARGO_STATION = 'warehouse_cargo_station/insert',
    LIST_WAREHOUSE_CARGO_STATION = 'warehouse_cargo_station',
    INSERT_PAYMENT_METHOD = 'payment_methods/insert',
    LIST_PAYMENT_METHODS = 'payment_methods',
    INSERT_USER_LEVEL = 'user_levels/insert',
    LIST_USER_LEVELS = 'user_levels',
    INSERT_LINE_CLASSIFICATION = 'line_classification/insert',
    LIST_LINE_CLASSIFICATION = 'line_classification',
    LIST_REGIONAL_DIVISION = 'regional_division',
    LIST_ORGANIZATION = 'users',
    LIST_AIR_GUIDE = 'manifest',
    LIST_SUMMARY = 'summary',
};
